spring:
  mvc:
    static-path-pattern: "/assets/**"
  cloud:
    config:
      uri: "http://localhost:9000/api/config-server/raw"
      username: xxxx
      password: xxxx
      enabled: false
  profiles:
    active: dev
frontend:
  type: "REACT"
leveldb:
  path: "leveldb/datas"
betaserie:
  apikey: "a8dd8ebe25e9"
  url: "https://api.betaseries.com"
tvdb:
  apikey: "92466265017F27E4"
  url: "https://api.thetvdb.com"
  banner: "https://www.thetvdb.com/banners/"
izanami:
  host: http://localhost:9000/
  client-id: xxxx
  client-secret: xxxx
  backend: SseBackend
  feature:
    strategy:
      type: CacheWithSseStrategy
      polling-interval: 1 seconds
      patterns: [mytvshows:*]
    fallback: >
      [
        { "id": "mytvshows:season:markaswatched", "enabled": false },
        { "id": "mytvshows:providers:tvdb", "enabled": true },
        { "id": "mytvshows:providers:betaserie", "enabled": false }
      ]
  proxy:
    feature:
      patterns: mytvshows:*
